In [20]:
import numpy as np

In [21]:
A = np.array([[0, 1], [2, 3],[4, 5]])

In [22]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [24]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
dot = np.dot(A, B)

In [26]:
dot

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [27]:
dot.max()

np.int64(47)